.\" This manpage is Copyright (C) 2000 Wei Yongming
.\"                               2000 BluePoint Software
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since MiniGUI is constantly changing, this
.\" manual page may be incorrect or out-of-date. The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" Modified 2000/11/30 by Wei Yongming.

.TH "minigui" "3" "August 2000" "MiniGUI"

.SH "NAME"
minigui \- Guide for manpages of MiniGUI version 1.x.

.SH "DESCRIPTION"
.TP
.BR miniguiFunctions (3)
Function list of MiniGUI version 1.x. Gives the brief description for functions of MiniGUI.
.TP
.BR miniguiMessages (3)
Message list of MiniGUI version 1.x. Gives the brief description for messages of MiniGUI.
.TP
.BR miniguiStructures (3)
Structure list of MiniGUI version 1.x. Gives the brief description for structures of MiniGUI.
.TP
.BR miniguiControls (3)
Brief description of usage of MiniGUI built-in controls.

.SH "AUTHOR"
.PP
This manual page was edited by Wei Yongming <ymwei@minigui.org>.
If you have any problems, comments or found some bugs, please send messages to me.

