.\" This manpage is Copyright (C) 2000 Wei Yongming
.\"                               2000 BluePoint Software
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Since MiniGUI is constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.TH "String" "3" "July 2000" "MiniGUI"

.SH "NAME"
String \- the string operation helpers of MiniGUI 

.SH "SYNOPSIS"
.B #include <minigui/minigui.h>
.PP
.BI "char* strnchr" "(const char* s, size_t n, int c);"
.PP
.BI "int substrlen" "(const char* text, int len, char delimiter, int* nr_delim);"

.SH "DESCRIPTION"
.PP
The \fBstrchr()\fP function returns a pointer to the first occurrence of the character \fBc\fP in the first \fBn\fP characters of string \fBs\fP. This function is similar with \fBstrchr\fP in ANSI C.
.PP
The \fBsubstrlen\fP function returns the length of the sub-string in the first \fBlen\fP characters of string \fBtext\fP. The sub-string is delimited with \fBdelimiter\fP from other character in the string. This function also returns number of continuous delimiters in \fBnr_delim\fP.

.SH "SEE ALSO"
.BR strchr (3)

.SH "AUTHOR"
.PP
This manual page was edited by WEI Yongming <ymwei@minigui.org>.
If you have any problems, comments or found some bugs, please send messages to me.

