.TH "Hook" "3" "August 2000" "MiniGUI"

.SH "NAME"
Hook \- hook function in MiniGUI.

.SH "SYNOPSIS"
.B #include <minigui/window.h>
.br

.PP
.BI "HHOOK GUIAPI RegisterKeyMsgHook" "(HWND hWnd, KEYMSGHOOK hook);"
.br
.BI "HHOOK GUIAPI RegisterMouseMsgHook" "(HWND hWnd, MOUSEMSGHOOK hook);"
.br
.BI "int GUIAPI UnregisterHook" "(HHOOK hHook);"

.SH "DESCRIPTION"
.PP
\fBRegisterKeyMsgHook\fP function registers a key message hook pointed to by \fBhook\fP and associates with the main window \fBhwnd\fP. This function returns the handle to the registered hook.
.PP
\fBRegisterMouseMsgHook\fP function registers a mouse message hook pointed to by \fBhook\fP and associate with the main window \fBhwnd\fP. This function returns the handle to the registered hook.
.PP
\fBUnregisterHook\fP function removes the key or mouse message hook specified by the handle of \fBhook\fP. 

.SH "RETURN VALUE"
.PP

.SH "NOTE"
.PP

.SH "SEE ALSO"

.SH "AUTHOR"
.PP
This manual page was edited by Kevin <kevin@minigui.org>.
If you have any problems, comments or found some bugs, please send messages to me.
