/* mgbidi-unicode-version.h
 * generated by gen-unicode-version
 * from the file ReadMe.txt */

#define MGBIDI_UNICODE_VERSION "12.0.0"
#define MGBIDI_UNICODE_MAJOR_VERSION 12
#define MGBIDI_UNICODE_MINOR_VERSION 0
#define MGBIDI_UNICODE_MICRO_VERSION 0

/* End of generated mgbidi-unicode-version.h */
