#ifndef _TFCODE_H
    #define _TFCODE_H

#define FUNCCODE_NONE		-1

// for front panel
#define FUNCCODE_VIDEOMODE	(SCANCODE_USER+1)
#define FUNCCODE_MENU		(SCANCODE_USER+2)
#define FUNCCODE_DISCEXCH	(SCANCODE_USER+3)
#define FUNCCODE_VOLUP		(SCANCODE_USER+4)
#define FUNCCODE_VOLDOWN	(SCANCODE_USER+5)
#define FUNCCODE_PLAYPAUSE	(SCANCODE_USER+6)
#define FUNCCODE_STOP		(SCANCODE_USER+7)
#define FUNCCODE_SF		(SCANCODE_USER+8)
#define FUNCOCDE_EJECT		(SCANCODE_USER+9)
#define FUNCCODE_FB		(SCANCODE_USER+10)
#define FUNCCODE_FF		(SCANCODE_USER+11)
#define FUNCCODE_PREVIOUS	(SCANCODE_USER+12)
#define FUNCCODE_NEXT		(SCANCODE_USER+13)

// for remote control
#define FUNCCODE_SR		(SCANCODE_USER+14)
#define FUNCCODE_CLEAR		(SCANCODE_USER+15)
#define FUNCCODE_POWER		(SCANCODE_USER+16)
#define FUNCCODE_OPMODE		(SCANCODE_USER+17)
#define FUNCCODE_UP		(SCANCODE_USER+18)
#define FUNCCODE_DOWN		(SCANCODE_USER+19)
#define FUNCCODE_LEFT		(SCANCODE_USER+20)
#define FUNCCODE_RIGHT		(SCANCODE_USER+21)
#define FUNCCODE_SELECT		(SCANCODE_USER+22)
#define FUNCCODE_SETUP		(SCANCODE_USER+23)
#define FUNCCODE_MUTE		(SCANCODE_USER+24)
#define FUNCCODE_LR		(SCANCODE_USER+25)
#define FUNCCODE_AUDIOMODE	(SCANCODE_USER+26)
#define FUNCCODE_3D		(SCANCODE_USER+27)
#define FUNCCODE_EQ		(SCANCODE_USER+28)
#define FUNCCODE_KARAOKE	(SCANCODE_USER+29)
#define FUNCCODE_PROG		(SCANCODE_USER+30)
#define FUNCCODE_TITLE		(SCANCODE_USER+31)
#define FUNCCODE_ANGLE		(SCANCODE_USER+32)
#define FUNCCODE_AB		(SCANCODE_USER+33)
#define FUNCCODE_REPEAT		(SCANCODE_USER+34)
#define FUNCCODE_ZOOM		(SCANCODE_USER+35)
#define FUNCCODE_OSD		(SCANCODE_USER+36)
#define FUNCCODE_LANG		(SCANCODE_USER+37)
#define FUNCCODE_SUBTITLE	(SCANCODE_USER+38)
#define FUNCCODE_DISPLAY	(SCANCODE_USER+39)
#define FUNCCODE_EMAIL		(SCANCODE_USER+40)
#define FUNCCODE_WEB		(SCANCODE_USER+41)
#define FUNCCODE_START		(SCANCODE_USER+42)
#define FUNCCODE_REFRESH	(SCANCODE_USER+43)
#define FUNCCODE_ENLARGE	(SCANCODE_USER+44)
#define FUNCCODE_FAVORITE	(SCANCODE_USER+45)
#define FUNCCODE_ESC		(SCANCODE_USER+46)

// for ir keyboard
#define FUNCCODE_APP		(SCANCODE_USER+47)
#define FUNCCODE_MACRO		(SCANCODE_USER+48)
#define FUNCCODE_SLEEP		(SCANCODE_USER+49)
#define FUNCCODE_WAKEUP		(SCANCODE_USER+50)
#define FUNCCODE_EJECT		(SCANCODE_USER+51)
#define FUNCCODE_LEFTWIN	(SCANCODE_USER+52)
#define FUNCCODE_RIGHTWIN	(SCANCODE_USER+53)



#endif
